import {
  CategoryItem,
  GalleryItem,
  VideoItem,
  TimelineEvent,
  TestimonialItem,
  FaqItem,
  InstagramPost,
  AchievementItem,
} from './types';

export const CONTACT_INFO = {
  phone: '+919899979654',
  phoneDisplay: '+91 98999 79654',
  email: 'info.kreativecornerz@gmail.com',
  whatsapp: 'https://wa.me/919899979654',
  instagram: 'https://www.instagram.com/magician_aman?igsh=MTV4Y2libzU1bWRkcg==',
  facebook: 'https://www.facebook.com/share/1ENEJuems6/',
};

export const STATISTICS = [
  { value: 1500, suffix: '+', label: 'Performances Nationwide' },
  { value: 100000, suffix: '+', label: 'Audience Members Amazed' },
  { value: 150, suffix: '+', label: 'Celebrity & Corporate VIPs' },
  { value: 10, suffix: '+ Yrs', label: 'Since First Spark' },
];

export const CLIENT_LOGOS = [
  { name: 'Taj Hotels', id: 'logo-1' },
  { name: 'Mercedes-Benz', id: 'logo-2' },
  { name: 'Reliance', id: 'logo-3' },
  { name: 'ITC Limited', id: 'logo-4' },
  { name: 'Oberoi Group', id: 'logo-5' },
  { name: 'DLF', id: 'logo-6' },
  { name: 'Infosys', id: 'logo-7' },
  { name: 'GMR Group', id: 'logo-8' },
];

export const TIMELINE_EVENTS: TimelineEvent[] = [
  {
    id: 't1',
    year: 'Prodigy',
    title: 'The Spark of Wonder',
    subtitle: 'Indian Magic Beginnings',
    description: 'Deeply drawn to the art of illusion, Aman begins learning card manipulation and sleight of hand at age 17, starting his lifelong chronicle of spreading magic.',
  },
  {
    id: 't2',
    year: 'Touring',
    title: 'Amaze, Astonish & Entertain',
    subtitle: 'National Presence',
    description: 'Tours extensively across India, mastering close-up table magic and grand-scale stage illusions capable of commanding and captivating audiences of any size.',
  },
  {
    id: 't3',
    year: 'Elite',
    title: 'With Bollywood Celebrities',
    subtitle: 'High-Profile Milestones',
    description: 'Establishes himself as the celebrity-favored conjurer, performing close-up and mentalism for stars like Saif Ali Khan, Farah Khan, Shilpa Shinde, Salim Merchant, and Singer KK.',
  },
  {
    id: 't4',
    year: 'Versatile',
    title: 'High-Altitude Illusions',
    subtitle: 'Aviation Parlor Feat',
    description: 'Pioneers versatile close-up magic by executing a fully interactive performance inside a flying commercial airliner cabin, bringing spectacular wonder to travelers.',
  },
  {
    id: 't5',
    year: 'Present',
    title: 'Western Style Stage Magic',
    subtitle: 'Modern Professional Approach',
    description: 'Redefines the craft, delivering a highly sophisticated blend of sleight of hand, telekinetic mentalism, and flame illusions with natural humor and elegant style.',
  },
];

export const CATEGORIES: CategoryItem[] = [
  {
    id: 'cat-corp',
    title: 'Corporate Galas',
    description: 'Sophisticated psychological illusions and mind-reading customized to engage your employees, clients, and partners, creating beautiful memories and laughter in astonishment.',
    icon: 'Briefcase',
    image: '/src/assets/images/aman_fire_magic_1784455570971.jpg',
    exampleIllusion: 'The Shared Thought: Unlocking a CEO’s mobile device live on stage based entirely on psychological readings.',
    highlightDetails: [
      'Tailored corporate message weaving',
      'Dynamic interactive icebreakers',
      'High-profile stage presence',
    ],
  },
  {
    id: 'cat-wedding',
    title: 'Luxury Weddings',
    description: 'Stunning close-up table magic during receptions and custom stage acts that add an elegant, dreamy aura of romance and prestige to your special day.',
    icon: 'Sparkles',
    image: '/src/assets/images/aman_portrait_cards_1784455511754.jpg',
    exampleIllusion: 'The Ring Transposition: A wedding ring vanishes and instantly appears locked in a box held by the bride.',
    highlightDetails: [
      'Sophisticated mix-and-mingle',
      'Family-focused visual storytelling',
      'Exclusive high-fashion attire',
    ],
  },
  {
    id: 'cat-stage',
    title: 'Grand Stage Shows',
    description: 'A colorful, modern Western-style stage magic show combining flame control, high-energy sleight of hand, and telekinetic illusions that challenge physical laws.',
    icon: 'Tv',
    image: '/src/assets/images/aman_umbrellas_1784455541777.jpg',
    exampleIllusion: 'The Blue Umbrella Production: Effortlessly conjuring open umbrellas from thick stage smoke.',
    highlightDetails: [
      'Large theater and ballroom scaling',
      'Stunning fire and light coordination',
      'Natural humor and charming style',
    ],
  },
  {
    id: 'cat-private',
    title: 'VIP Private Soirées',
    description: 'Ultra-intimate, sophisticated magic for luxury residences, penthouses, and private gather-outs, leaving analytical minds questioning reality.',
    icon: 'Gem',
    image: '/src/assets/images/aman_portrait_cards_1784455511754.jpg',
    exampleIllusion: 'Telekinetic Sunglasses: Causing a pair of sunglasses to slide and rotate on the carpet with zero physical touch.',
    highlightDetails: [
      'Highly personal close-up focus',
      'Flexible, low-footprint design',
      'Sleight of hand inches from eyes',
    ],
  },
  {
    id: 'cat-others',
    title: 'Others / Custom Showcase',
    description: 'Ground-up illusion production tailored for unique venue architectures, product launches, television broadcasts, and bespoke event concepts.',
    icon: 'Layers',
    image: '/src/assets/images/aman_tuxedo_fan_1785058897057.jpg',
    exampleIllusion: 'Custom Illusion Engineering: Creating custom magical reveals designed around your specific brand, venue, or storyline.',
    highlightDetails: [
      'Original illusion concepts',
      'Site-specific performance staging',
      'Custom brand & story integration',
    ],
  },
];

export const GALLERY_ITEMS: GalleryItem[] = [
  {
    id: 'gal-1',
    url: 'https://lh3.googleusercontent.com/d/143nmuRx4yWftTgoIrb7BlV3Vf-dzDraW',
    title: 'The Portrait of a Conjurer',
    category: 'Sleight of Hand',
    description: 'Magician Aman holding a flawless fan of playing cards in his tuxedo, capturing his modern professional approach.',
    aspectRatio: 'portrait',
  },
  {
    id: 'gal-2',
    url: 'https://lh3.googleusercontent.com/d/1vM5mHXICFpnS1zUd5-lcEMLEUZ-SLr8t',
    title: 'Close-Up Sleight of Hand',
    category: 'Live Shows',
    description: 'Aman showcasing card choices and interactive psychological sleight of hand for guests.',
    aspectRatio: 'portrait',
  },
  {
    id: 'gal-3',
    url: '/src/assets/images/aman_fire_magic_1784455570971.jpg',
    title: 'Chamber of Fire',
    category: 'Stage Illusions',
    description: 'A spectacular Western-style illusion where flames ignite from a closed leather book, demonstrating mastery of visual heat.',
    aspectRatio: 'landscape',
  },
  {
    id: 'gal-4',
    url: '/src/assets/images/aman_umbrellas_1784455541777.jpg',
    title: 'Blue Umbrella Production',
    category: 'Stage Illusions',
    description: 'Producing large blue umbrellas out of thin air, a legendary visual conjuring routine that commands major stage sets.',
    aspectRatio: 'portrait',
  },
  {
    id: 'gal-5',
    url: '/src/assets/images/aman_fire_magic_1784455570971.jpg',
    title: 'High-Altitude Magic',
    category: 'Private VIP',
    description: 'Bringing wonder to the sky. Aman performing close-up card miracles inside a flying passenger airplane cabin.',
    aspectRatio: 'portrait',
  },
  {
    id: 'gal-6',
    url: '/src/assets/images/aman_umbrellas_1784455541777.jpg',
    title: 'Backstage with Singer KK',
    category: 'Live Shows',
    description: 'A classic, heartfelt moment backstage performing close-up sleight of hand for the legendary late Indian playback singer KK.',
    aspectRatio: 'square',
  },
  {
    id: 'gal-7',
    url: '/src/assets/images/aman_portrait_cards_1784455511754.jpg',
    title: 'Laughter & Astonishment',
    category: 'Private VIP',
    description: 'Engaging families and private party groups with table magic, leaving them smiling and laughing in pure amazement.',
    aspectRatio: 'landscape',
  },
  {
    id: 'gal-8',
    url: '/src/assets/images/aman_fire_magic_1784455570971.jpg',
    title: 'With Shilpa Shinde ("Anguri Bhabhi")',
    category: 'Mentalism',
    description: 'Performing mind reading and card transpositions for the beloved actress Shilpa Shinde, creating sheer joy.',
    aspectRatio: 'square',
  },
];

export const VIDEO_ITEMS: VideoItem[] = [
  {
    id: 'vid-showreel',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    title: 'Illusionist Aman: Cinematic Master Showreel',
    duration: '2:15',
    category: 'Master Reel',
    description: 'A premium high-production showreel combining Aman’s national stage tours, flame wallet transpositions, celebrity mentalism, and interactive close-up sleight of hand across prestigious events.',
    thumbnail: '/src/assets/images/aman_umbrellas_1784455541777.jpg',
  },
  {
    id: 'vid-1',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    title: 'Direct Table Deception: The Vanishing Deck',
    duration: '0:22',
    category: 'Sleight of Hand',
    description: 'Witness close-up card sleight of hand performed directly at a dinner table. Aman vanishes a full deck of cards right under the spectator’s observation, finding their signed selection in an impossible location.',
    thumbnail: '/src/assets/images/aman_portrait_cards_1784455511754.jpg',
  },
  {
    id: 'vid-2',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    title: 'Street Magic Sparks: The Organic Card Change',
    duration: '0:22',
    category: 'Private VIP',
    description: 'A raw, unedited reaction captured at an outdoor lawn party. Aman places a card in a child’s palm, which visually changes into another card under their own hand, sparking screams of disbelief.',
    thumbnail: '/src/assets/images/aman_portrait_cards_1784455511754.jpg',
  },
  {
    id: 'vid-3',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    title: 'Levitating Glasses: Telekinetic Energy',
    duration: '0:17',
    category: 'Mentalism',
    description: 'In this live, highly scrutinized parlor act, Aman kneels on the floor and uses telekinetic focus to cause a pair of heavy spectator glasses to slide, rotate, and lift off the ground without strings or wires.',
    thumbnail: '/src/assets/images/aman_portrait_cards_1784455511754.jpg',
  },
  {
    id: 'vid-4',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    title: 'Sleight at the Bar: Signed Card Transposition',
    duration: '0:30',
    category: 'Sleight of Hand',
    description: 'A high-speed signed card illusion performed at an elite cocktail bar. Watch as a card chosen by a guest swaps places with another card held by Aman in a fraction of a second.',
    thumbnail: '/src/assets/images/aman_umbrellas_1784455541777.jpg',
  },
  {
    id: 'vid-5',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    title: 'Intimate parlor Magic: Sponge Ball Duplication',
    duration: '0:15',
    category: 'Sleight of Hand',
    description: 'A classic interactive crowd-pleaser. Aman places two small red sponge balls in a spectator\'s hand, which multiply to four when she opens her palm, evoking absolute delight.',
    thumbnail: '/src/assets/images/aman_portrait_cards_1784455511754.jpg',
  },
  {
    id: 'vid-6',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutback2013.mp4',
    title: 'Mind Synchronization: Guessing the Bill Number',
    duration: '0:41',
    category: 'Mentalism',
    description: 'Aman performs mind reading for a corporate leader, revealing details of a private currency note serial number and secret thoughts under direct, unedited spotlight observation.',
    thumbnail: '/src/assets/images/aman_fire_magic_1784455570971.jpg',
  },
  {
    id: 'vid-7',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
    title: 'Telekinesis Live: Sunglasses Slide',
    duration: '0:45',
    category: 'Mentalism',
    description: 'A second close-up perspective of the telekinetic sunglasses manipulation. Watch the glasses slide across a slick marble table under a heavy glass container, completely defying physics.',
    thumbnail: '/src/assets/images/aman_fire_magic_1784455570971.jpg',
  },
  {
    id: 'vid-8',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    title: 'Interactive Table Sync: Spectator Choice',
    duration: '1:03',
    category: 'Private VIP',
    description: 'A group of six guests sits around a table making a sequence of entirely free, chaotic choices with cards. Aman reveals a pre-written letter predicting their exact decisions.',
    thumbnail: '/src/assets/images/aman_portrait_cards_1784455511754.jpg',
  },
  {
    id: 'vid-9',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    title: 'Chamber of Fire: Wallet Ignite & Signed Card',
    duration: '1:40',
    category: 'Stage Illusions',
    description: 'A spectacular transition combining fire magic with card mechanics. Aman opens his wallet, which bursts into a blazing inferno, before producing a signed, folded card from inside.',
    thumbnail: '/src/assets/images/aman_umbrellas_1784455541777.jpg',
  },
];

export const TESTIMONIALS: TestimonialItem[] = [
  {
    id: 'test-1',
    name: 'Rajesh Malhotra',
    role: 'Managing Director, Luxury Hospitality',
    company: 'Oberoi Hotels & Resorts, Mumbai',
    rating: 5,
    text: 'Illusionist Aman turned our flagship annual gala into an unforgettable spectacle. His psychological mentalism left our global dignitaries completely spellbound. Absolute elegance and world-class mastery.',
    avatar: '',
  },
  {
    id: 'test-2',
    name: 'Ananya Deshmukh',
    role: 'Head of Corporate Communications',
    company: 'Reliance Industries, Mumbai',
    rating: 5,
    text: 'Aman seamlessly wove our corporate vision into his live stage performance. The way he read minds and engaged over 500 senior executives was nothing short of miraculous. The most talked-about artist we have ever hosted.',
    avatar: '',
  },
  {
    id: 'test-3',
    name: 'Vikramaditya Singhania',
    role: 'Founder & Event Architect',
    company: 'Singhania Heritage & Royal Weddings, Jaipur',
    rating: 5,
    text: 'In destination luxury weddings, guests expect unprecedented grandeur. Aman’s close-up sleight of hand during the royal reception was pure magic. Every single guest was thoroughly mesmerized and delighted.',
    avatar: '',
  },
  {
    id: 'test-4',
    name: 'Priya Nair',
    role: 'Executive Director',
    company: 'Infosys Leadership Summit, Bengaluru',
    rating: 5,
    text: 'Having witnessed stage performers across the world, Aman’s intellect, natural humor, and psychological illusions stand in a league of their own. He had our tech leaders questioning the laws of physics.',
    avatar: '',
  },
  {
    id: 'test-5',
    name: 'Karan Kapoor',
    role: 'Vice President of Marketing',
    company: 'DLF Cybercity, New Delhi',
    rating: 5,
    text: 'Aman performed for our exclusive VIP penthouse launch in Delhi. His intimate style, charm, and flame transpositions created an atmosphere of pure prestige. Exceptionally brilliant.',
    avatar: '',
  },
  {
    id: 'test-6',
    name: 'Sunita Aggarwal',
    role: 'Chief Experience Officer',
    company: 'ITC Grand Chola Celebrations, Chennai',
    rating: 5,
    text: 'Aman brings unmatched sophistication to the stage. His blue umbrella production and interactive mind synchronization were the absolute highlight of our national leadership summit.',
    avatar: '',
  },
];

export const INSTAGRAM_FEED: InstagramPost[] = [
  {
    id: 'ig-1',
    imageUrl: '/src/assets/images/aman_portrait_cards_1784455511754.jpg',
    likes: 1240,
    comments: 88,
    caption: 'Moments before the curtains part. Stepping into the void. #IllusionistAman #GenevaTheater #BehindTheMagic',
    date: '3d ago',
  },
  {
    id: 'ig-2',
    imageUrl: '/src/assets/images/aman_umbrellas_1784455541777.jpg',
    likes: 2190,
    comments: 142,
    caption: 'Reality is but a beautifully constructed canvas. Let’s repaint it together. #SleightOfHand #VisualIllusion #AestheticMagic',
    date: '1w ago',
  },
  {
    id: 'ig-3',
    imageUrl: '/src/assets/images/aman_fire_magic_1784455570971.jpg',
    likes: 1850,
    comments: 95,
    caption: 'Reflections on mental synchronization. Thank you to the incredible team at Louis Vuitton. #CorporateGalas #Mentalism #LuxuryEvents',
    date: '2w ago',
  },
  {
    id: 'ig-4',
    imageUrl: '/src/assets/images/aman_portrait_cards_1784455511754.jpg',
    likes: 3102,
    comments: 205,
    caption: 'Tools of the trade. Every details designed to evoke elegant mystery. #ClassicVibe #PremiumAesthetic #Craft',
    date: '3w ago',
  },
];

export const WHY_CHOOSE_ITEMS = [
  {
    title: 'Absolute Professionalism',
    description: 'Impeccable communication, punctuality, and presentation. Tailored to suit high-end corporate, VIP, or diplomatic requirements.',
    icon: 'ShieldCheck',
  },
  {
    title: 'Immersive Mind Reading',
    description: 'Advanced psychological mentalism that leaves even the most analytical minds questioning their free will and understanding of reality.',
    icon: 'Eye',
  },
  {
    title: 'Audience Participation',
    description: 'Interactive illusions where the spectators themselves perform the impossible, becoming the true heroes of the magic.',
    icon: 'Users',
  },
  {
    title: 'Bespoke Performances',
    description: 'Each showcase is customized specifically for your event’s theme, message, or spatial design to ensure total exclusivity.',
    icon: 'Sliders',
  },
];

export const FAQS: FaqItem[] = [
  {
    id: 'faq-1',
    question: 'What types of shows do you specialize in?',
    answer: 'Illusionist Aman specializes in high-end Corporate Galas, Luxury Weddings, VIP Private Soirées, and Grand Stage Shows. Every performance is crafted with a sophisticated, mysterious, and highly interactive presentation, strictly avoiding outdated magic clichés.',
  },
  {
    id: 'faq-2',
    question: 'How far in advance should we book a performance?',
    answer: 'Bookings should ideally be made a minimum of 10 days in advance. While we avoid creating artificial urgency, last-minute requests can also be considered if the calendar has an open slot.',
  },
  {
    id: 'faq-4',
    question: 'What are the technical requirements for a stage show?',
    answer: 'Technical specifications vary depending on the venue size and show choice. Generally, a professional sound system, localized stage lighting, and a microphone are required. For grand illusions, a detailed technical rider covering lighting, fog/smoke, and backline specifications will be sent to your AV team.',
  },
  {
    id: 'faq-5',
    question: 'Do you perform close-up magic or stage magic?',
    answer: 'Both, often combined. Sleight of hand (close-up magic) is perfect for standing receptions, cocktail hours, or VIP parlor tables where magic happens inches from the eyes. Stage mentalism is better suited for seated banquets, theaters, or corporate auditoriums up to 1,000 guests.',
  },
];
